version: '3.4'

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis
     
  mongo-express:
    image: mongo-express

  catalog.api:
    container_name: catalogapi

  basket.api:
    container_name: basketapi
 
