
version: '3.4'


services:

  catalogdb:
    image: mongo

  cachedb:
    image: redis

#  orderdb:
#    image: mcr.microsoft.com/mssql/server
#  
#  identitydb:
#    image: mcr.microsoft.com/mssql/server

  sqlserverdb:
    image: mcr.microsoft.com/mssql/server

  #message broker
  rabbitmq:
    image: rabbitmq:3-management-alpine

  identity.api:
    container_name: identityapi

  gateway.api:
    container_name: gatewayapi

  catalog.api:
    container_name: catalogapi

  basket.api:
    container_name: basketapi
 
  ordering.api:
    container_name: orderingapi
    
  mongo-express:
    image: mongo-express

  web:
    image: ${DOCKER_REGISTRY-}web


