version: '3.4'

services:

  catalogdb:
    container_name: catalogdb
    restart: always
    #volumes:
        #- ${WEBAPP_STORAGE_HOME}/site:/data/db
        #- ./data:/data/db
    ports:
        - 27017:27017
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  basketdb:
    container_name: basketdb
    restart: always
    ports:
        - 6379:6379

  orderdb:
    container_name: orderdb
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "AGG_123654789"
      ACCEPT_EULA: "Y"

  catalog.api:
    container_name: catalogapi
    restart: on-failure
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "CatalogDatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    image: ${DOCKER_REGISTRY-}catalogapi
    ports:
      - 8010:80
    depends_on:
        - catalogdb
    #volumes:
     #- ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
     #- ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    build:
      context: .
      dockerfile: src/catalog/catalog.api/Dockerfile

  basket.api:
    container_name: basketapi
    restart: on-failure
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "ConnectionStrings:Redis=basketdb:6379"
        - "EventBus:HostName=rabbitmq"
    image: ${DOCKER_REGISTRY-}basketapi
    ports:
      - 8020:80
    depends_on:
        - basketdb
        - rabbitmq
    #volumes:
     #- ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
     #- ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    build:
      context: .
      dockerfile: src/basket/basket.api/Dockerfile

  ordering.api:
    container_name: orderingapi
    restart: on-failure
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        #- "ConnectionStrings:Redis=basketdb:6379"
        - "EventBus:HostName=rabbitmq"
    image: ${DOCKER_REGISTRY-}orderingapi
    ports:
      - 8030:80
    depends_on:
        - orderdb
        - rabbitmq
    #volumes:
     #- ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
     #- ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    build:
      context: .
      dockerfile: src/ordering/ordering.api/Dockerfile

  gateway.api:
    container_name: gatewayapi
    restart: on-failure
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    image: ${DOCKER_REGISTRY-}gatewayapi
    ports:
      - 8040:80
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api
    #volumes:
     #- ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
     #- ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    build:
      context: .
      dockerfile: src/gateway/gateway.api/Dockerfile

  mongo-express:
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - catalogdb        
    environment:
      ME_CONFIG_MONGODB_SERVER: catalogdb
