# Use root/example as user/password credentials
version: '3.1'

services:

  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    #volumes:
        #- ${WEBAPP_STORAGE_HOME}/site:/data/db
        #- ./data:/data/db
    ports:
        - "27017:27017"

      #networks:
      #  mongo_net:
      #    ipv4_address: 172.16.0.1
      #command: mongod --bind_ip 0.0.0.0
      #environment:
      #  MONGO_INITDB_ROOT_USERNAME: root
      #  MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - catalogdb        
    environment:
      ME_CONFIG_MONGODB_SERVER: catalogdb
    #  ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #  ME_CONFIG_MONGODB_ADMINPASSWORD: example

  catalog.api:
    container_name: catalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    image: ${DOCKER_REGISTRY-}catalogapi
    ports:
        - "8000:80"   
    build:
        context: .
        dockerfile: src/catalog/catalog.api/Dockerfile
    depends_on:
        - catalogdb    
#networks:
#  mongo_net:
#    driver: bridge
#      ipam:
#      config:
#      - subnet: 172.16.0.0/24
#        gateway: 172.16.0.254      